# Generated by Django 5.2.8 on 2025-11-21 15:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DebtPlan', '0003_alter_debtplan_total_interest_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterToSelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('debt_plan', models.OneToOneField(help_text='The debt plan this letter is for', on_delete=django.db.models.deletion.CASCADE, related_name='completion_letter', to='DebtPlan.debtplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_to_self', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter to Self',
                'verbose_name_plural': 'Letters to Self',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_plans/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('debt_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan_pdf', to='DebtPlan.debtplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Plan PDF',
                'verbose_name_plural': 'Payment Plan PDFs',
                'ordering': ['-generated_at'],
            },
        ),
    ]
