# Generated by Django 5.2.8 on 2025-11-15 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Debt Freedom Plan', max_length=255)),
                ('strategy', models.CharField(choices=[('snowball', 'Snowball Method'), ('avalanche', 'Avalanche Method')], max_length=20)),
                ('monthly_payment_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projected_payoff_date', models.DateField(blank=True, null=True)),
                ('total_interest_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
