# Generated by Django 5.2.8 on 2025-11-19 21:42

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtPlan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='debtplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='debtplan',
            name='monthly_payment_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='debtplan',
            name='total_interest_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='debtplan',
            index=models.Index(fields=['user', 'is_active'], name='DebtPlan_de_user_id_e3aa65_idx'),
        ),
    ]
