# Generated by Django 5.2.8 on 2025-11-19 23:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtPlan', '0002_alter_debtplan_options_debtplan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtplan',
            name='total_interest_saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
