# Generated by Django 5.2.8 on 2025-11-19 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DebtPlan', '0002_alter_debtplan_options_debtplan_updated_at_and_more'),
        ('Loan', '0002_alter_loan_options_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('check', 'Check'), ('cash', 'Cash'), ('auto_pay', 'Automatic Payment'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('is_extra_payment', models.BooleanField(default=False)),
                ('is_below_minimum', models.BooleanField(default=False)),
                ('month_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmation_number', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='DebtPlan.debtplan')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Loan.loan')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['loan', 'payment_date'], name='Payment_pay_loan_id_391862_idx'), models.Index(fields=['debt_plan', 'payment_date'], name='Payment_pay_debt_pl_585699_idx'), models.Index(fields=['payment_method'], name='Payment_pay_payment_c21be4_idx'), models.Index(fields=['-payment_date'], name='Payment_pay_payment_2ee3a2_idx')],
            },
        ),
    ]
