# Generated by Django 5.2.8 on 2025-11-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtPlan', '0003_alter_debtplan_total_interest_saved'),
        ('Loan', '0002_alter_loan_options_alter_loan_interest_rate_and_more'),
        ('Payment', '0001_initial'),
        ('PaymentSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, help_text='The scheduled month this payment fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_payments', to='PaymentSchedule.paymentschedule'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_schedule'], name='Payment_pay_payment_6ae08d_idx'),
        ),
    ]
