# Generated by Django 5.2.8 on 2025-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_payment_payment_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_timing',
            field=models.CharField(blank=True, choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late')], help_text='Whether payment was made early, on-time, or late', max_length=10, null=True),
        ),
    ]
