# Generated by Django 5.2.8 on 2025-12-07 13:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_payment_payment_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_before_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loan balance before this payment was applied', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest amount calculated at time of payment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal amount calculated at time of payment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
