# Generated by Django 5.2.8 on 2025-11-19 21:42

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DebtPlan', '0002_alter_debtplan_options_debtplan_updated_at_and_more'),
        ('Loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['payoff_order', 'created_at']},
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'debt_plan'], name='Loan_loan_user_id_5a0b24_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['payoff_order'], name='Loan_loan_payoff__2ca89d_idx'),
        ),
    ]
