# Generated by Django 5.2.8 on 2025-11-19 22:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DebtPlan', '0002_alter_debtplan_options_debtplan_updated_at_and_more'),
        ('Loan', '0002_alter_loan_options_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_principal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='DebtPlan.debtplan')),
                ('focus_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focused_schedules', to='Loan.loan')),
            ],
            options={
                'ordering': ['month_number'],
            },
        ),
        migrations.CreateModel(
            name='LoanPaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_focus_loan', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_breakdowns', to='Loan.loan')),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_breakdowns', to='PaymentSchedule.paymentschedule')),
            ],
            options={
                'ordering': ['loan__payoff_order'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['debt_plan', 'month_number'], name='PaymentSche_debt_pl_785b2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together={('debt_plan', 'month_number')},
        ),
        migrations.AddIndex(
            model_name='loanpaymentschedule',
            index=models.Index(fields=['payment_schedule', 'loan'], name='PaymentSche_payment_5c2111_idx'),
        ),
    ]
